# environment:
matrix:
  include:
    # Python 2.7
    - MINICONDA: C:\Miniconda
      platform: x86
    - MINICONDA: C:\Miniconda-x64
      platform: x64
    # Python 3.4
    - MINICONDA: C:\Miniconda3
      platform: x86
    - MINICONDA: C:\Miniconda3-x64
      platform: x64
    # Python 3.5
    - MINICONDA: C:\Miniconda35
      platform: x86
    - MINICONDA: C:\Miniconda35-x64
      platform: x64
    # Python 3.6
    - MINICONDA: C:\Miniconda36
      platform: x86
    - MINICONDA: C:\Miniconda36-x64
      platform: x64

init:
  - ps: if($env:Platform -eq "x86"){$MINICONDA = "C:\Miniconda36"}
  - ps: if($env:Platform -eq "x64"){$MINICONDA = "C:\Miniconda36-x64"}
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda create -q -n test-environment python=$PYTHON_VERSION pip openblas numpy scipy
  - source activate test-environment
  - "pip install -q nose"
  - "pip install 'coverage<4'"  # After 4, there is some issue when using python 3.2
  - "pip install -qr requirements.txt"
  - "echo done"

# command to run tests, e.g. python setup.py test
test_script: 
  - nosetests --with-coverage --cover-package=mcfly

after_test:
  - "pip install scrutinizer-ocular"
  - "ocular"
